import { readFileSync, writeFileSync } from 'fs';
const p = 'app/span/span-html.ts';
let c = readFileSync(p, 'utf8');
const BS = String.fromCharCode(92);
const QT = String.fromCharCode(34);
c = c.split(BS + QT + '&rdquo;').join('&mdash;');
c = c.split(BS + QT + '&ldquo;').join('&mdash;');
writeFileSync(p, c, 'utf8');
const v = readFileSync(p, 'utf8');
const i = v.indexOf('Syntra v2');
console.log(JSON.stringify(v.substring(i, i+55)));